/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ForgotPassword200Response
 */
export interface ForgotPassword200Response {
  /**
   *
   * @type {string}
   * @memberof ForgotPassword200Response
   */
  token?: string;
  /**
   *
   * @type {Date}
   * @memberof ForgotPassword200Response
   */
  expiresAt?: Date;
}

/**
 * Check if a given object implements the ForgotPassword200Response interface.
 */
export function instanceOfForgotPassword200Response(value: object): value is ForgotPassword200Response {
  return true;
}

export function ForgotPassword200ResponseFromJSON(json: any): ForgotPassword200Response {
  return ForgotPassword200ResponseFromJSONTyped(json, false);
}

export function ForgotPassword200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPassword200Response {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"] == null ? undefined : json["token"],
    expiresAt: json["expiresAt"] == null ? undefined : new Date(json["expiresAt"]),
  };
}

export function ForgotPassword200ResponseToJSON(json: any): ForgotPassword200Response {
  return ForgotPassword200ResponseToJSONTyped(json, false);
}

export function ForgotPassword200ResponseToJSONTyped(value?: ForgotPassword200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
    expiresAt: value["expiresAt"] == null ? value["expiresAt"] : value["expiresAt"].toISOString(),
  };
}
