/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Goal
 */
export interface Goal {
  /**
   *
   * @type {string}
   * @memberof Goal
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof Goal
   */
  amount?: number;
  /**
   *
   * @type {string}
   * @memberof Goal
   */
  walletId?: string;
  /**
   *
   * @type {string}
   * @memberof Goal
   */
  startingDate?: string;
  /**
   *
   * @type {string}
   * @memberof Goal
   */
  endingDate?: string;
  /**
   *
   * @type {string}
   * @memberof Goal
   */
  id?: string;
}

/**
 * Check if a given object implements the Goal interface.
 */
export function instanceOfGoal(value: object): value is Goal {
  return true;
}

export function GoalFromJSON(json: any): Goal {
  return GoalFromJSONTyped(json, false);
}

export function GoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Goal {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    amount: json["amount"] == null ? undefined : json["amount"],
    walletId: json["walletId"] == null ? undefined : json["walletId"],
    startingDate: json["startingDate"] == null ? undefined : json["startingDate"],
    endingDate: json["endingDate"] == null ? undefined : json["endingDate"],
    id: json["id"] == null ? undefined : json["id"],
  };
}

export function GoalToJSON(json: any): Goal {
  return GoalToJSONTyped(json, false);
}

export function GoalToJSONTyped(value?: Goal | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    amount: value["amount"],
    walletId: value["walletId"],
    startingDate: value["startingDate"],
    endingDate: value["endingDate"],
    id: value["id"],
  };
}
