/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ResetPassword200Response
 */
export interface ResetPassword200Response {
  /**
   *
   * @type {string}
   * @memberof ResetPassword200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the ResetPassword200Response interface.
 */
export function instanceOfResetPassword200Response(value: object): value is ResetPassword200Response {
  return true;
}

export function ResetPassword200ResponseFromJSON(json: any): ResetPassword200Response {
  return ResetPassword200ResponseFromJSONTyped(json, false);
}

export function ResetPassword200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPassword200Response {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
  };
}

export function ResetPassword200ResponseToJSON(json: any): ResetPassword200Response {
  return ResetPassword200ResponseToJSONTyped(json, false);
}

export function ResetPassword200ResponseToJSONTyped(value?: ResetPassword200Response | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
  };
}
