/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AccountAccountIdGoalGet200Response, CreationGoal, Goal } from "../models/index";
import {
  AccountAccountIdGoalGet200ResponseFromJSON,
  AccountAccountIdGoalGet200ResponseToJSON,
  CreationGoalFromJSON,
  CreationGoalToJSON,
  GoalFromJSON,
  GoalToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface AccountAccountIdGoalGetRequest {
  accountId: string;
  name?: string;
  startingDate?: string;
  endingDate?: string;
}

export interface AccountAccountIdGoalGoalIdGetRequest {
  accountId: string;
}

export interface AccountAccountIdGoalGoalIdPutRequest {
  accountId: string;
  goal?: Goal;
}

export interface AccountAccountIdGoalPostRequest {
  accountId: string;
  creationGoal?: CreationGoal;
}

/**
 *
 */
export class GoalApi extends runtime.BaseAPI {
  /**
   * Get all disponibles goal of one account
   */
  async accountAccountIdGoalGetRaw(
    requestParameters: AccountAccountIdGoalGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AccountAccountIdGoalGet200Response>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling accountAccountIdGoalGet().');
    }

    const queryParameters: any = {};

    if (requestParameters["name"] != null) {
      queryParameters["name"] = requestParameters["name"];
    }

    if (requestParameters["startingDate"] != null) {
      queryParameters["startingDate"] = requestParameters["startingDate"];
    }

    if (requestParameters["endingDate"] != null) {
      queryParameters["endingDate"] = requestParameters["endingDate"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => AccountAccountIdGoalGet200ResponseFromJSON(jsonValue));
  }

  /**
   * Get all disponibles goal of one account
   */
  async accountAccountIdGoalGet(
    requestParameters: AccountAccountIdGoalGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AccountAccountIdGoalGet200Response> {
    const response = await this.accountAccountIdGoalGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async accountAccountIdGoalGoalIdGetRaw(
    requestParameters: AccountAccountIdGoalGoalIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Goal>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling accountAccountIdGoalGoalIdGet().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * Get one goal of one account by it\'s id
   */
  async accountAccountIdGoalGoalIdGet(requestParameters: AccountAccountIdGoalGoalIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.accountAccountIdGoalGoalIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * update one goal of one account
   */
  async accountAccountIdGoalGoalIdPutRaw(
    requestParameters: AccountAccountIdGoalGoalIdPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Goal>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling accountAccountIdGoalGoalIdPut().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/goal/{goalId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: GoalToJSON(requestParameters["goal"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
  }

  /**
   * update one goal of one account
   */
  async accountAccountIdGoalGoalIdPut(requestParameters: AccountAccountIdGoalGoalIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
    const response = await this.accountAccountIdGoalGoalIdPutRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * create new goal for one account
   */
  async accountAccountIdGoalPostRaw(
    requestParameters: AccountAccountIdGoalPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AccountAccountIdGoalGet200Response>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling accountAccountIdGoalPost().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/goal`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreationGoalToJSON(requestParameters["creationGoal"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => AccountAccountIdGoalGet200ResponseFromJSON(jsonValue));
  }

  /**
   * create new goal for one account
   */
  async accountAccountIdGoalPost(
    requestParameters: AccountAccountIdGoalPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AccountAccountIdGoalGet200Response> {
    const response = await this.accountAccountIdGoalPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
